# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facturacion.ui'
#
# Created: Sun Mar 15 12:24:19 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Facturacion(object):
    def setupUi(self, Facturacion):
        Facturacion.setObjectName(_fromUtf8("Facturacion"))
        Facturacion.resize(650, 420)
        Facturacion.setMaximumSize(QtCore.QSize(650, 420))
        Facturacion.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lblBazarPapeleriaLulita = QtGui.QLabel(Facturacion)
        self.lblBazarPapeleriaLulita.setGeometry(QtCore.QRect(200, 0, 240, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lblBazarPapeleriaLulita.setFont(font)
        self.lblBazarPapeleriaLulita.setStyleSheet(_fromUtf8("Color:rgb(51, 102, 255);"))
        self.lblBazarPapeleriaLulita.setObjectName(_fromUtf8("lblBazarPapeleriaLulita"))
        self.lblDireccion = QtGui.QLabel(Facturacion)
        self.lblDireccion.setGeometry(QtCore.QRect(110, 20, 420, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lblDireccion.setFont(font)
        self.lblDireccion.setStyleSheet(_fromUtf8("Color:rgb(51, 102, 255);"))
        self.lblDireccion.setObjectName(_fromUtf8("lblDireccion"))
        self.txtClient = QtGui.QLineEdit(Facturacion)
        self.txtClient.setGeometry(QtCore.QRect(109, 60, 501, 25))
        self.txtClient.setObjectName(_fromUtf8("txtClient"))
        self.txtTotal = QtGui.QLineEdit(Facturacion)
        self.txtTotal.setGeometry(QtCore.QRect(500, 320, 105, 25))
        self.txtTotal.setObjectName(_fromUtf8("txtTotal"))
        self.btnRegresar = QtGui.QPushButton(Facturacion)
        self.btnRegresar.setGeometry(QtCore.QRect(50, 380, 260, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnRegresar.setFont(font)
        self.btnRegresar.setMouseTracking(True)
        self.btnRegresar.setStyleSheet(_fromUtf8("Color:rgb(223, 15, 90);"))
        self.btnRegresar.setObjectName(_fromUtf8("btnRegresar"))
        self.lblSubtotal = QtGui.QLabel(Facturacion)
        self.lblSubtotal.setGeometry(QtCore.QRect(40, 320, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblSubtotal.setFont(font)
        self.lblSubtotal.setObjectName(_fromUtf8("lblSubtotal"))
        self.lblCliente = QtGui.QLabel(Facturacion)
        self.lblCliente.setGeometry(QtCore.QRect(40, 60, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCliente.setFont(font)
        self.lblCliente.setObjectName(_fromUtf8("lblCliente"))
        self.lblFecha = QtGui.QLabel(Facturacion)
        self.lblFecha.setGeometry(QtCore.QRect(40, 90, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblFecha.setFont(font)
        self.lblFecha.setObjectName(_fromUtf8("lblFecha"))
        self.lblIva = QtGui.QLabel(Facturacion)
        self.lblIva.setGeometry(QtCore.QRect(240, 320, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblIva.setFont(font)
        self.lblIva.setObjectName(_fromUtf8("lblIva"))
        self.lblPago = QtGui.QLabel(Facturacion)
        self.lblPago.setGeometry(QtCore.QRect(240, 350, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPago.setFont(font)
        self.lblPago.setObjectName(_fromUtf8("lblPago"))
        self.lblTotal = QtGui.QLabel(Facturacion)
        self.lblTotal.setGeometry(QtCore.QRect(450, 320, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotal.setFont(font)
        self.lblTotal.setObjectName(_fromUtf8("lblTotal"))
        self.lblVuelto = QtGui.QLabel(Facturacion)
        self.lblVuelto.setGeometry(QtCore.QRect(450, 350, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblVuelto.setFont(font)
        self.lblVuelto.setObjectName(_fromUtf8("lblVuelto"))
        self.txtVuelto = QtGui.QLineEdit(Facturacion)
        self.txtVuelto.setGeometry(QtCore.QRect(500, 350, 105, 25))
        self.txtVuelto.setObjectName(_fromUtf8("txtVuelto"))
        self.txtPago = QtGui.QLineEdit(Facturacion)
        self.txtPago.setGeometry(QtCore.QRect(310, 350, 105, 25))
        self.txtPago.setObjectName(_fromUtf8("txtPago"))
        self.txtIva = QtGui.QLineEdit(Facturacion)
        self.txtIva.setGeometry(QtCore.QRect(310, 320, 105, 25))
        self.txtIva.setObjectName(_fromUtf8("txtIva"))
        self.txtSubtotal = QtGui.QLineEdit(Facturacion)
        self.txtSubtotal.setGeometry(QtCore.QRect(110, 320, 105, 25))
        self.txtSubtotal.setText(_fromUtf8(""))
        self.txtSubtotal.setObjectName(_fromUtf8("txtSubtotal"))
        self.txtFecha = QtGui.QLineEdit(Facturacion)
        self.txtFecha.setGeometry(QtCore.QRect(109, 90, 501, 25))
        self.txtFecha.setObjectName(_fromUtf8("txtFecha"))
        self.btnImprimir = QtGui.QPushButton(Facturacion)
        self.btnImprimir.setGeometry(QtCore.QRect(330, 380, 260, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnImprimir.setFont(font)
        self.btnImprimir.setMouseTracking(True)
        self.btnImprimir.setStyleSheet(_fromUtf8("Color:rgb(1, 137, 125);"))
        self.btnImprimir.setObjectName(_fromUtf8("btnImprimir"))
        self.tblVwFacturacion = QtGui.QListWidget(Facturacion)
        self.tblVwFacturacion.setGeometry(QtCore.QRect(40, 160, 565, 145))
        self.tblVwFacturacion.setMouseTracking(True)
        self.tblVwFacturacion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tblVwFacturacion.setAutoFillBackground(False)
        self.tblVwFacturacion.setDragDropOverwriteMode(True)
        self.tblVwFacturacion.setProperty("isWrapping", False)
        self.tblVwFacturacion.setGridSize(QtCore.QSize(0, 0))
        self.tblVwFacturacion.setModelColumn(0)
        self.tblVwFacturacion.setUniformItemSizes(False)
        self.tblVwFacturacion.setObjectName(_fromUtf8("tblVwFacturacion"))
        item = QtGui.QListWidgetItem()
        self.tblVwFacturacion.addItem(item)
        self.txtBuscar = QtGui.QLineEdit(Facturacion)
        self.txtBuscar.setGeometry(QtCore.QRect(50, 130, 432, 25))
        self.txtBuscar.setAutoFillBackground(True)
        self.txtBuscar.setObjectName(_fromUtf8("txtBuscar"))
        self.btnIngresar = QtGui.QCommandLinkButton(Facturacion)
        self.btnIngresar.setGeometry(QtCore.QRect(480, 120, 70, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnIngresar.sizePolicy().hasHeightForWidth())
        self.btnIngresar.setSizePolicy(sizePolicy)
        self.btnIngresar.setMouseTracking(True)
        self.btnIngresar.setAutoFillBackground(False)
        self.btnIngresar.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/buscar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIngresar.setIcon(icon)
        self.btnIngresar.setIconSize(QtCore.QSize(70, 40))
        self.btnIngresar.setCheckable(True)
        self.btnIngresar.setAutoExclusive(False)
        self.btnIngresar.setObjectName(_fromUtf8("btnIngresar"))

        self.retranslateUi(Facturacion)
        QtCore.QMetaObject.connectSlotsByName(Facturacion)

    def retranslateUi(self, Facturacion):
        Facturacion.setWindowTitle(_translate("Facturacion", "Facturacion", None))
        self.lblBazarPapeleriaLulita.setText(_translate("Facturacion", "BAZAR Y PAPELERIA LULITA", None))
        self.lblDireccion.setText(_translate("Facturacion", "Km 8 1/2 via Daule - Cdla. \"La Gaviota\" Mz. 2262 V. 7", None))
        self.txtClient.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">Cliente</span></p></body></html>", None))
        self.txtClient.setPlaceholderText(_translate("Facturacion", "Nombre del cliente", None))
        self.txtTotal.setToolTip(_translate("Facturacion", "<html><head/><body><p>Total</p></body></html>", None))
        self.txtTotal.setPlaceholderText(_translate("Facturacion", "Total", None))
        self.btnRegresar.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">REGRESAR</span></p></body></html>", None))
        self.btnRegresar.setText(_translate("Facturacion", "REGRESAR", None))
        self.lblSubtotal.setText(_translate("Facturacion", "Subtotal", None))
        self.lblCliente.setText(_translate("Facturacion", "CLiente", None))
        self.lblFecha.setText(_translate("Facturacion", "Fecha", None))
        self.lblIva.setText(_translate("Facturacion", "IVA 12%", None))
        self.lblPago.setText(_translate("Facturacion", "Pago", None))
        self.lblTotal.setText(_translate("Facturacion", "Total", None))
        self.lblVuelto.setText(_translate("Facturacion", "Vuelto", None))
        self.txtVuelto.setToolTip(_translate("Facturacion", "<html><head/><body><p>Vuelto</p></body></html>", None))
        self.txtVuelto.setPlaceholderText(_translate("Facturacion", "Vuelto", None))
        self.txtPago.setToolTip(_translate("Facturacion", "<html><head/><body><p>Pagó</p></body></html>", None))
        self.txtPago.setPlaceholderText(_translate("Facturacion", "Pagó", None))
        self.txtIva.setToolTip(_translate("Facturacion", "<html><head/><body><p>IVA 12%</p></body></html>", None))
        self.txtIva.setPlaceholderText(_translate("Facturacion", "IVA 12%", None))
        self.txtSubtotal.setToolTip(_translate("Facturacion", "<html><head/><body><p>Subtotal</p></body></html>", None))
        self.txtSubtotal.setPlaceholderText(_translate("Facturacion", "Subtotal", None))
        self.txtFecha.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">Fecha</span></p></body></html>", None))
        self.txtFecha.setPlaceholderText(_translate("Facturacion", "Fecha en la que se efectua la factura", None))
        self.btnImprimir.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">IMPRIMIR</span></p></body></html>", None))
        self.btnImprimir.setText(_translate("Facturacion", "IMPRIMIR", None))
        self.tblVwFacturacion.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">Detalle</span></p></body></html>", None))
        self.tblVwFacturacion.setWhatsThis(_translate("Facturacion", "Cantidades", None))
        __sortingEnabled = self.tblVwFacturacion.isSortingEnabled()
        self.tblVwFacturacion.setSortingEnabled(False)
        item = self.tblVwFacturacion.item(0)
        item.setText(_translate("Facturacion", "Cantidad", None))
        self.tblVwFacturacion.setSortingEnabled(__sortingEnabled)
        self.txtBuscar.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\"> Buscar producto</span></p></body></html>", None))
        self.txtBuscar.setPlaceholderText(_translate("Facturacion", "Buscar producto del Bazar y Papeleria ", None))
        self.btnIngresar.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">Ingresar producto</span></p></body></html>", None))


