# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facturacion.ui'
#
# Created: Fri May  1 10:59:38 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Facturacion(object):
    def setupUi(self, Facturacion):
        Facturacion.setObjectName(_fromUtf8("Facturacion"))
        Facturacion.resize(650, 420)
        Facturacion.setMinimumSize(QtCore.QSize(650, 420))
        Facturacion.setMaximumSize(QtCore.QSize(650, 420))
        Facturacion.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tbVwFactura = QtGui.QTableWidget(Facturacion)
        self.tbVwFactura.setGeometry(QtCore.QRect(20, 160, 600, 150))
        self.tbVwFactura.setObjectName(_fromUtf8("tbVwFactura"))
        self.tbVwFactura.setColumnCount(0)
        self.tbVwFactura.setRowCount(0)
        self.txtSubtotal = QtGui.QLineEdit(Facturacion)
        self.txtSubtotal.setGeometry(QtCore.QRect(120, 320, 120, 25))
        self.txtSubtotal.setText(_fromUtf8(""))
        self.txtSubtotal.setObjectName(_fromUtf8("txtSubtotal"))
        self.lblBazarPapeleriaLulita = QtGui.QLabel(Facturacion)
        self.lblBazarPapeleriaLulita.setGeometry(QtCore.QRect(210, 0, 251, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lblBazarPapeleriaLulita.setFont(font)
        self.lblBazarPapeleriaLulita.setStyleSheet(_fromUtf8("Color:rgb(51, 102, 255);"))
        self.lblBazarPapeleriaLulita.setObjectName(_fromUtf8("lblBazarPapeleriaLulita"))
        self.lblSubtotal = QtGui.QLabel(Facturacion)
        self.lblSubtotal.setGeometry(QtCore.QRect(50, 320, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblSubtotal.setFont(font)
        self.lblSubtotal.setObjectName(_fromUtf8("lblSubtotal"))
        self.lblTotal = QtGui.QLabel(Facturacion)
        self.lblTotal.setGeometry(QtCore.QRect(460, 320, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotal.setFont(font)
        self.lblTotal.setObjectName(_fromUtf8("lblTotal"))
        self.txtTotal = QtGui.QLineEdit(Facturacion)
        self.txtTotal.setGeometry(QtCore.QRect(520, 320, 105, 25))
        self.txtTotal.setObjectName(_fromUtf8("txtTotal"))
        self.lblCliente = QtGui.QLabel(Facturacion)
        self.lblCliente.setGeometry(QtCore.QRect(30, 60, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCliente.setFont(font)
        self.lblCliente.setObjectName(_fromUtf8("lblCliente"))
        self.txtVuelto = QtGui.QLineEdit(Facturacion)
        self.txtVuelto.setGeometry(QtCore.QRect(520, 350, 105, 25))
        self.txtVuelto.setObjectName(_fromUtf8("txtVuelto"))
        self.txtIva = QtGui.QLineEdit(Facturacion)
        self.txtIva.setGeometry(QtCore.QRect(330, 320, 120, 25))
        self.txtIva.setObjectName(_fromUtf8("txtIva"))
        self.btnEliminar = QtGui.QPushButton(Facturacion)
        self.btnEliminar.setGeometry(QtCore.QRect(510, 130, 90, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEliminar.sizePolicy().hasHeightForWidth())
        self.btnEliminar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setMouseTracking(True)
        self.btnEliminar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEliminar.setAutoFillBackground(False)
        self.btnEliminar.setStyleSheet(_fromUtf8("color:rgb(170, 0, 127)"))
        self.btnEliminar.setIconSize(QtCore.QSize(100, 25))
        self.btnEliminar.setCheckable(True)
        self.btnEliminar.setAutoRepeat(False)
        self.btnEliminar.setAutoExclusive(False)
        self.btnEliminar.setAutoRepeatDelay(300)
        self.btnEliminar.setObjectName(_fromUtf8("btnEliminar"))
        self.lblIva = QtGui.QLabel(Facturacion)
        self.lblIva.setGeometry(QtCore.QRect(250, 320, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblIva.setFont(font)
        self.lblIva.setObjectName(_fromUtf8("lblIva"))
        self.lblDireccion = QtGui.QLabel(Facturacion)
        self.lblDireccion.setGeometry(QtCore.QRect(120, 20, 431, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lblDireccion.setFont(font)
        self.lblDireccion.setStyleSheet(_fromUtf8("Color:rgb(51, 102, 255);"))
        self.lblDireccion.setObjectName(_fromUtf8("lblDireccion"))
        self.lblVuelto = QtGui.QLabel(Facturacion)
        self.lblVuelto.setGeometry(QtCore.QRect(460, 350, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblVuelto.setFont(font)
        self.lblVuelto.setObjectName(_fromUtf8("lblVuelto"))
        self.lblCedula = QtGui.QLabel(Facturacion)
        self.lblCedula.setGeometry(QtCore.QRect(30, 90, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCedula.setFont(font)
        self.lblCedula.setObjectName(_fromUtf8("lblCedula"))
        self.lblPago = QtGui.QLabel(Facturacion)
        self.lblPago.setGeometry(QtCore.QRect(250, 350, 70, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPago.setFont(font)
        self.lblPago.setObjectName(_fromUtf8("lblPago"))
        self.lblDireccionCleinte = QtGui.QLabel(Facturacion)
        self.lblDireccionCleinte.setGeometry(QtCore.QRect(290, 90, 71, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblDireccionCleinte.setFont(font)
        self.lblDireccionCleinte.setObjectName(_fromUtf8("lblDireccionCleinte"))
        self.cbxCliente = QtGui.QComboBox(Facturacion)
        self.cbxCliente.setGeometry(QtCore.QRect(100, 60, 491, 25))
        self.cbxCliente.setObjectName(_fromUtf8("cbxCliente"))
        self.cbxCedula = QtGui.QComboBox(Facturacion)
        self.cbxCedula.setGeometry(QtCore.QRect(100, 90, 181, 25))
        self.cbxCedula.setObjectName(_fromUtf8("cbxCedula"))
        self.txtDireccion = QtGui.QLineEdit(Facturacion)
        self.txtDireccion.setGeometry(QtCore.QRect(360, 90, 231, 25))
        self.txtDireccion.setText(_fromUtf8(""))
        self.txtDireccion.setObjectName(_fromUtf8("txtDireccion"))
        self.cbxProducto = QtGui.QComboBox(Facturacion)
        self.cbxProducto.setGeometry(QtCore.QRect(30, 130, 460, 25))
        self.cbxProducto.setObjectName(_fromUtf8("cbxProducto"))
        self.txtPago = QtGui.QLineEdit(Facturacion)
        self.txtPago.setGeometry(QtCore.QRect(330, 350, 120, 25))
        self.txtPago.setObjectName(_fromUtf8("txtPago"))
        self.btnGuardar = QtGui.QPushButton(Facturacion)
        self.btnGuardar.setGeometry(QtCore.QRect(245, 380, 190, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnGuardar.setFont(font)
        self.btnGuardar.setMouseTracking(True)
        self.btnGuardar.setStyleSheet(_fromUtf8("color:rgb(72, 145, 217)"))
        self.btnGuardar.setObjectName(_fromUtf8("btnGuardar"))
        self.btnImprimir = QtGui.QPushButton(Facturacion)
        self.btnImprimir.setGeometry(QtCore.QRect(435, 380, 190, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnImprimir.setFont(font)
        self.btnImprimir.setMouseTracking(True)
        self.btnImprimir.setStyleSheet(_fromUtf8("Color:rgb(1, 137, 125);"))
        self.btnImprimir.setObjectName(_fromUtf8("btnImprimir"))
        self.btnRegresar = QtGui.QPushButton(Facturacion)
        self.btnRegresar.setGeometry(QtCore.QRect(50, 380, 190, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnRegresar.setFont(font)
        self.btnRegresar.setMouseTracking(True)
        self.btnRegresar.setStyleSheet(_fromUtf8("Color:rgb(223, 15, 90);"))
        self.btnRegresar.setObjectName(_fromUtf8("btnRegresar"))

        self.retranslateUi(Facturacion)
        QtCore.QMetaObject.connectSlotsByName(Facturacion)

    def retranslateUi(self, Facturacion):
        Facturacion.setWindowTitle(_translate("Facturacion", "Facturacion", None))
        self.txtSubtotal.setToolTip(_translate("Facturacion", "<html><head/><body><p>Subtotal</p></body></html>", None))
        self.txtSubtotal.setPlaceholderText(_translate("Facturacion", "Subtotal", None))
        self.lblBazarPapeleriaLulita.setText(_translate("Facturacion", "BAZAR Y PAPELERIA LULITA", None))
        self.lblSubtotal.setText(_translate("Facturacion", "Subtotal", None))
        self.lblTotal.setText(_translate("Facturacion", "Total", None))
        self.txtTotal.setToolTip(_translate("Facturacion", "<html><head/><body><p>Total</p></body></html>", None))
        self.txtTotal.setPlaceholderText(_translate("Facturacion", "Total", None))
        self.lblCliente.setText(_translate("Facturacion", "CLiente", None))
        self.txtVuelto.setToolTip(_translate("Facturacion", "<html><head/><body><p>Vuelto</p></body></html>", None))
        self.txtVuelto.setPlaceholderText(_translate("Facturacion", "Vuelto", None))
        self.txtIva.setToolTip(_translate("Facturacion", "<html><head/><body><p>IVA 12%</p></body></html>", None))
        self.txtIva.setPlaceholderText(_translate("Facturacion", "IVA 12%", None))
        self.btnEliminar.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">Ingresar producto</span></p></body></html>", None))
        self.btnEliminar.setText(_translate("Facturacion", "ELIMINAR", None))
        self.lblIva.setText(_translate("Facturacion", "IVA 12%", None))
        self.lblDireccion.setText(_translate("Facturacion", "Km 8 1/2 via Daule - Cdla. \"La Gaviota\" Mz. 2262 V. 7", None))
        self.lblVuelto.setText(_translate("Facturacion", "Vuelto", None))
        self.lblCedula.setText(_translate("Facturacion", "Cedula", None))
        self.lblPago.setText(_translate("Facturacion", "Pago", None))
        self.lblDireccionCleinte.setText(_translate("Facturacion", "Direccion", None))
        self.cbxCliente.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\"> Buscar producto</span></p></body></html>", None))
        self.cbxCedula.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\"> Buscar producto</span></p></body></html>", None))
        self.txtDireccion.setToolTip(_translate("Facturacion", "<html><head/><body><p>Subtotal</p></body></html>", None))
        self.txtDireccion.setPlaceholderText(_translate("Facturacion", "Direccion domiciliaria", None))
        self.cbxProducto.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\"> Buscar producto</span></p></body></html>", None))
        self.txtPago.setToolTip(_translate("Facturacion", "<html><head/><body><p>Pagó</p></body></html>", None))
        self.txtPago.setPlaceholderText(_translate("Facturacion", "Pagó", None))
        self.btnGuardar.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">IMPRIMIR</span></p></body></html>", None))
        self.btnGuardar.setText(_translate("Facturacion", "GUARDAR", None))
        self.btnImprimir.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">IMPRIMIR</span></p></body></html>", None))
        self.btnImprimir.setText(_translate("Facturacion", "IMPRIMIR", None))
        self.btnRegresar.setToolTip(_translate("Facturacion", "<html><head/><body><p><span style=\" color:#ffffff;\">REGRESAR</span></p></body></html>", None))
        self.btnRegresar.setText(_translate("Facturacion", "REGRESAR", None))
